FROM python:3.11-slim

ENV PORT=8080
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/
COPY models/ ./models/

CMD exec uvicorn app.main:app --host 0.0.0.0 --port ${PORT}
